pylutron_caseta/smartbridge.py
tests/test_smartbridge.py

With enough lights, it gets very easy to have a name collision. In Home Assistant, the device names change each time HASS is restarted, causing unreliable control of devices. Using the fully qualified name fixes this issue by naming devices in a more global fashion.
Fixes #18

Use fully qualified names for devices

---

.gitignore
get_lutron_cert.py
pylutron_caseta/smartbridge.py

It looks like with the new firmware:
- certificates have been reissued
- the bridge sends some unsolicited messages on connection
- the names of devices have been prefixed with the names of rooms? My Home Assistant was not happy after patching this code in, but it could have been something I did in the Lutron app when I installed new switches a couple weeks ago.
The existing script to get the certificates should still get the certificates, despite printing an error at the end. I've put an updated copy of the script directly in the repository.
Unexpected messages are now ignored during the connection phase. If you're somehow still running the old firmware this shouldn't be a problem.
Fixes #22

Support Spring 2018 protocol

---

pylutron_caseta/smartbridge.py
tests/test_smartbridge.py

In order to support the [Home Assistant Entity Registry](https://www.home-assistant.io/docs/configuration/entity-registry/) we need to be able to construct a stable identifier value for every device. I don't know the details of how Lutron issues serial numbers, but I assume a combination of model ID and serial number will be unique within every home.

add model and serial to device listing

---

get_lutron_cert.py
pylutron_caseta/smartbridge.py

It looks like in a recent firmware update the bridge started sending different certificates when the client sends a server name indication extension (SNI) in TLS client hello message. Unfortunately, pylutron-caseta does send such extensions if run on a version of Python that supports it, but get_lutron_cert.py does not.
At first I tried making get_lutron_cert.py support SNI like smartbridge.py does, but that would mean everybody needs to rerun get_lutron_cert.py to get new certificates. Additionally, when I went to try this on my Home Assistant server I found that it doesn't seem to support SNI so the certificates I'd collected on my desktop did not work on my server, meaning users could encounter cases such as mine where the certificates work until they're placed on the server, but also …

be consistent about how TLS handshaking is done

---

get_lutron_cert.py

This version of get_lutron_cert does not depend on Lutron web services (which have disappeared), or even having a Lutron cloud account at all. You pair with the bridge device by pressing the button on the back while the script is running.

rewrite get_lutron_cert

---

pylutron_caseta/smartbridge.py

Sometimes Python incorrectly reports OSError "No route to host" which does not derive from ConnectionError when you fail to create a network connection. pylutron_caseta should continue attempting to reconnect if it gets such an error.
This just retries after any OSError. It doesn't try to figure out what OS its running on and what that error code means for the current OS.
Fixes #45

treat OSError like ConnectionError

---

pylintrc
pylutron_caseta/smartbridge.py
tests/responses/devices.json
tests/test_smartbridge.py

I'm working on a Home Assistant PR to add SUPPORT_STOP to covers

Add Raise/Lower/Stop support for covers

---

.devcontainer/devcontainer.json
.flake8
.travis.yml
pylutron_caseta/__init__.py
pylutron_caseta/leap.py
pylutron_caseta/smartbridge.py
requirements_test.txt
setup.py
tests/test_leap.py
tests/test_smartbridge.py
tox.ini

All files have been reformatted and some minor linter complaints have been addressed.
Python versions 3.5 and 3.6 are no longer supported.
The only functional difference is that now when `id_from_href` raises an exception the source exception information is included.

update tools and add black

---

pylintrc
pylutron_caseta/__init__.py
pylutron_caseta/leap.py
pylutron_caseta/messages.py
pylutron_caseta/smartbridge.py
tests/test_leap.py
tests/test_smartbridge.py

LEAP implements an HTTP-like request+response interface over a single TLS over TCP connection using newlines for framing and JSON objects for message serialization. Responses are correlated with their requests by a ClientTag value sent along with the request. The server can push information to the client by sending responses to requests that were not sent, in which case no ClientTag value will be sent on the response message.
Previously, pylutron_caseta was sending requests without ClientTags and discarding most responses. For example, set_level was asynchronous, but not a coroutine because SmartBridge had no way of knowing if the bridge received the message at all once the request was put in the send buffer. The CreateResponse message the bridge command processor sent back upon receiving …

async requests with ClientTag

---

CHANGELOG.md
pylintrc
pylutron_caseta/leap.py
pylutron_caseta/smartbridge.py
tests/test_leap.py
tests/test_smartbridge.py

Unlike the unsolicited status updates for lights, switches, etc, the occupancy group status updates must be subscribed to, and they are sent with the same tag value that was used for the original subscription.
Related: home-assistant/core#42620

expect tags on occupancy group updates

---

pylutron_caseta/leap.py

This should not matter in general because the LeapProtocol object itself is released by SmartBridge shortly after the connection is closed.

release subscriptions on disconnect

---

CHANGELOG.md
pylutron_caseta/smartbridge.py

This should fix a problem @gmcmicken reported on #60 where his occupancy groups stop updating in Home Assistant after restarting the bridge connection.

use setdefault for areas and occupancy

---

.gitignore

If user just checks out the git repo and follows the instructions in the header of `get_lutron_cert.py`, they get a python environment inside their copy of the git repo. Ignoring `/env/`  protects against that.

chore: ignore python environment

---

pylutron_caseta/__init__.py

The PD-15OUT connected to my smart hub identifies itself as being type `OutdoorPlugInSwitch`. This adds it to the switch domain.

Add support for PD-15OUT outdoor switches.

---

pylutron_caseta/__init__.py
pylutron_caseta/smartbridge.py
tests/responses/buttons.json
tests/responses/buttonsubscribe.json
tests/responses/devices.json
tests/test_smartbridge.py

This code adds the ability to subscribe to Pico button events using LEAP.
A ReadRequest to /device will have some Pico devices. Each Pico will have a ButtonGroups tag with a buttongroup href and ID.  
A ReadRequest to /button will return a series of Buttons tag linked to the above button group. Each of these is a button on the Pico.  
As an example, a Pico device can have buttongroup 2, and that buttongroup can have buttons 103-107. 
To subscribe to event notifications, send a SubscribeRequest for each button ID. For 103, for example, you’d send the SubscribeRequest with the URL /button/103/status/event
Whenever you press or release that Pico button, you’ll get a ButtonStatus body with a ButtonEvent, and the EventType of “Press” or “Release”.
This code finds any devices with buttongroups, …

add support for pico button events

---

CHANGELOG.md
pylutron_caseta/pairing.py

Changes
---
* Updated `pairing.py` to check if the current OS is Windows to manually delete the temporary files
Reason for Changes
---
Fixes the `PermissionError: [Errno 13] Permission denied` error that is being thrown when `async_pair` is called on Windows.
Related Issues
---
https://github.com/gurumitts/pylutron-caseta/issues/93

Pairing: Manually delete temporary files on windows

---

CHANGELOG.md
pylutron_caseta/smartbridge.py
tests/test_smartbridge.py

Without a link between the two, there is no way to know which
device reported the occupancy status.
The device information contrains a list of OccupancySensors as
does the Occupancy group information.  So let's add the lists
into our public data structures so the link can be established.
For the device, we use the same method as button_groups to create
a new field called occupancy_sensors.
For the occupancy group we create an array from the
AssociatedSensors and add it as a new field called sensors.

Link Occupancy sensor device to Occupancy group.

---

pylutron_caseta/cli.py

The unpatched `leap-pair` CLI has a bug where the call to `async_pair()` was referencing the first character of `address`, which is a string. In the case of an address like 192.168.1.100, the pairing attempt would be made with "1" and returned the error:
```
OSError: [Errno 65] No route to host
```
This PR corrects this by removing the `[0]`. 
Tested by pairing with a Lutron QSX processor:
```
$ lap-pair x.x.x.x
Press the small black button on the back of the bridge to complete pairing.
Successfully paired with 3.223
```
Also tested with a Lutron Caseta bridge to ensure that functionality still worked:
```
$ lap-pair x.x.x.y
Press the small black button on the back of the bridge to complete pairing.
Successfully paired with 1.115
```
pytest shows all tests passing:

Fix bug where only the first character of the bridge/processor's IP address is used by lap-pair

---

pylutron_caseta/__init__.py

This PR adds support for a new occupancy sensor device type that has been discovered.
A user that has been helping with testing has a sensor with DeviceType "RPSCeilingMountedOccupancySensor"
Adding this sensor type to RA3_OCCUPANCY_SENSOR_DEVICE_TYPES enables this occupancy sensor.

RA3/QSX - Add support for RPSCeilingMountedOccupancySensor

---

pylutron_caseta/__init__.py

Adding support for the PhantomKeypad DeviceType.
The PhantomKeypad is the RA2 version of the RA3 HomeOwner Keypad. 
Both of these are virtual Keypads.
DeviceType has been confirmed on my own system.

Add support for PhantomKeypad

---

pylutron_caseta/cli.py

Apparently the _leap service is not used with the newer hardware. Home Assistant has its own version of this and should make the same change.

look for _lutron._tcp.local

---

CHANGELOG.md
pylutron_caseta/smartbridge.py
tests/test_smartbridge.py

Currently, the area discovery ignores any area that has the field IsLeaf: False
Unfortunately, this leads to a broken area tree for RA3/HWQSX if the area's don't contain any control stations or devices.
In the example below, both "tree 1" and "tree 2" areas are reported as having "None" parent, because the isLeaf field is False as a consequence of not containing any devices/control stations.
"tree 3" correctly reports it's parent as "tree 2"
This update ignores the IsLeaf field, and discovers all areas defined on the bridge/processor, maintaining the correct parent/child relationship.

Fix area tree discovery

---

pylutron_caseta/smartbridge.py

`PROTOCOL_TLSv1_2` has been deprecated since Python 3.6. Use `ssl.PROTOCOL_TLS_CLIENT` instead.
https://docs.python.org/3/library/ssl.html#ssl.SSLContext

Remove deprecated ssl.PROTOCOL_TLSv1_2

---

pylutron_caseta/__init__.py

The RA3 firmware that ships with the latest v23.4 Designer software changes the device type of wall mounted occupancy sensors in LEAP to "RPSWallMountedOccupancySensor," which was previously not a part of this library. This changes adds that device type. The new firmware also appears to change the device type of Phantom Keypads, however my debug logs only show device type as "Unknown," so someone with more architecture knowledge may need to step in and help with that change.

Add device type for Wall Mounted Motion Sensor in RA3 Firmware v23.4

---

pylutron_caseta/leap.py
pylutron_caseta/smartbridge.py

Reconnects could fail because the monitor loop would fail due to a request already being done
```
2023-09-26 08:10:57.188 CRITICAL (MainThread) [pylutron_caseta.smartbridge] monitor loop has exited
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/pylutron_caseta/smartbridge.py", line 484, in _monitor
await self._monitor_once()
File "/usr/local/lib/python3.11/site-packages/pylutron_caseta/smartbridge.py", line 536, in _monitor_once
self._leap.close()
File "/usr/local/lib/python3.11/site-packages/pylutron_caseta/leap.py", line 169, in close
request.set_exception(BridgeDisconnectedError())
asyncio.exceptions.InvalidStateError: invalid state
```
fixes https://github.com/home-assistant/core/issues/100958#issuecomment-1736207797

Fix reconnect race

---

.devcontainer/devcontainer.json

without "bash" at the start of this command, the devcontainer machinery invokes "sh -c ./.devcontainer/updateContent.sh". 
But this file is not executable, so we get a permissions denied error. Changing the command to
```
bash ./.devcontainer/updateContent.sh
```
tells the build machinery to invoke `bash` (which is executable) and use it to read and execute the specified script. Since `updateContent.sh` is readable, and since `bash` is executable, the build machinery is able to run the `updateContentCommand` script this way.
see https://github.com/gurumitts/pylutron-caseta/issues/158

invoke bash ./.devcontainer/updateContent.sh

---

src/pylutron_caseta/smartbridge.py

Using `pylutron-caseta` in Home Assistant, this code crashed on initialization. This change seems to handle the condition that was leading to the crash. See also https://github.com/home-assistant/core/issues/109095

Fix crash related to having no buttons in button group

---

src/pylutron_caseta/cli.py
src/pylutron_caseta/leap.py
src/pylutron_caseta/messages.py
src/pylutron_caseta/smartbridge.py

LEAP supports a pagination mechanism when it hits limits on the number of objects returned in a particular API call. I observed this when retrieving more than 99 areas on a QSX system here: https://github.com/gurumitts/pylutron-caseta/issues/152
The response header will contain a Paging object which has a ContinuationToken that should be reflected back into a subsequent request to continue returning additional results.
This PR adds paging support to both the leap client, for manual paging invocation, and the smartbridge interface, by repeating requests until all pagination is complete and the results are merged together.

add LEAP Paging/ContinuationToken support

---

LICENSE
pyproject.toml

Hey 👋🏻,
I am currently looking into licensing at Home Assistant, and I found that we could not detect the license of this library properly. According to pyproject.toml documentation about the `license` field:
> If you are using a standard, well-known license, it is not necessary to use this field. Instead, you should use one of the [classifiers](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#classifiers) starting with License ::. (As a general rule, it is a good idea to use a standard, well-known license, both to avoid confusion and because some organizations avoid software whose license is unapproved.)
If you could do a release after this PR, that would be awesome :)

Fix license classifier

---

pyproject.toml
src/pylutron_caseta/cli.py
src/pylutron_caseta/leap.py
src/pylutron_caseta/pairing.py
tests/test_leap.py
tests/test_smartbridge.py

Use orjson instead of json like home assistant does. pylutron-caseta spends a lot of time munging json and orjson is fast at that. The main compatibility difference between json and orjson is that dumps() returns bytes.

use orjson instead of json

---

src/pylutron_caseta/__init__.py
tests/responses/devices.json
tests/test_smartbridge.py

This pull request adds the "Tilt" device type, which is for the new wood blinds they released. 
This is for this issue in Home Assistant, where they are currently not being pulled in to HA
https://github.com/home-assistant/core/issues/115940#issuecomment-2564058946
@FloorLamp Tested my branch and confirmed everything worked as expected with his wood blinds

Add Tilt shade device type support

---

src/pylutron_caseta/smartbridge.py
tests/test_smartbridge.py

In HA we want to be able to timeout if connect fails but wait a long time for the initial setup of the subscriptions/data.
Fixes for a few cancellation races
HA PR https://github.com/home-assistant/core/pull/138875

Add support for getting a callback on connect success

---

src/pylutron_caseta/__init__.py

Adding support for new model SerenaEssentialsRollerShade (SYERX-B-X)
ex:
"32": {
"device_id": "32",
"current_state": 100,
"fan_speed": null,
"tilt": null,
"zone": "24",
"name": "Master Bedroom_Master Balcony Shade",
"button_groups": null,
"occupancy_sensors": null,
"type": "SerenaEssentialsRollerShade",
"model": "SYERX-B-X",
"serial": 141955679,
"device_name": "Master Balcony Shade",
"area": "6"
}

Update __init__.py to support SerenaEssentialsRollerShade

---

README.md

There is no event loop to "get", so the example fails.
Instead, use `asyncio.run()` to construct a loop, call the example function, and exit when `example()` completes.

use asyncio.run()

---

src/pylutron_caseta/__init__.py

Some Keypads, like Alisse, send a MultiTap event every time the user double presses a button. The added const makes it explicit, so integrators like Home Assistant can use it.

Adds a new button status to detect double press
